.TH EXISTS 1 2020-04-26
.SH NAME
exists \- check if files exist
.SH SYNOPSIS
.B exists
[\fB\-v\fR]
[\fB\-h\fR]
.SH DESCRIPTION
.B exists
reads filenames from STDIN, and prints filenames that exist to STDOUT
.SH OPTIONS
.TP
.BR \-h
show list of command-line options
.TP
.BR \-v
inverts output, print filenames that don't exist
.SH AUTHOR
Written by Sean Breckenridge
.SH SEE ALSO
Source code avaiable at <https://github.com/seanbreckenridge/exists>
